Next js doc changes
highlight-run/docs pull request #18
Opened 2022-12-14 07:12 UTC by jay-khatri

2022-12-14 18:31 UTC, Vadman97 requested changes
need to update `middleware.ts` to the new next path
![image](https://user-images.githubusercontent.com/1351531/207679696-9f998f19-541e-4257-b0b2-3400afd7bda1.png)

2022-12-14 18:31 UTC, Vadman97 commented on general-docs/2_getting-started/fullstack-frameworks/next-js/1_overview.md
> +--   automatic proxying for Highlight requests using Next.js rewrites: [withHighlightConfig()](/docs/sdk/nextjs#withHighlightConfig)
the double `--` makes the frontend not render this like a normal bulleted list

2022-12-16 05:39 UTC, jay-khatri commented on general-docs/2_getting-started/fullstack-frameworks/next-js/1_overview.md
> +--   server-side error monitoring and linking to Highlight sessions: [Highlight()](/docs/sdk/nextjs#Highlight)
why do the links in the `hint` in `angular.md` not work without the `/docs` path then?

2022-12-16 20:03 UTC, Vadman97 approved these changes

2022-12-16 20:03 UTC, merged

2022-12-16 20:07 UTC, Vadman97 commented on general-docs/2_getting-started/fullstack-frameworks/next-js/1_overview.md
> +--   server-side error monitoring and linking to Highlight sessions: [Highlight()](/docs/sdk/nextjs#Highlight)
looks like the `hint` [callout processing](https://github.com/highlight-run/highlight-landing/blob/main/components/Docs/Callout/Callout.tsx) is different and uses the regular `ReactMarkdown` processing. that's why the links actually reload the tab as well which is not great. filing a ticket to fix both.